// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYqvRSi0BbIUys_YN6tMAMOanSDaDLqu8',
    appId: '1:736748802815:web:8e73d781a691dc8a3d32ca',
    messagingSenderId: '736748802815',
    projectId: 'fir-register-c3602',
    authDomain: 'fir-register-c3602.firebaseapp.com',
    storageBucket: 'fir-register-c3602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0IZfcVXQZHYkkuE_gEf3_w6pNGwgszKs',
    appId: '1:736748802815:android:dbaa1891c234d21a3d32ca',
    messagingSenderId: '736748802815',
    projectId: 'fir-register-c3602',
    storageBucket: 'fir-register-c3602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU9J63C7nT5WWXnZIXZXZezbCY6XBQZHg',
    appId: '1:736748802815:ios:5f491fc97054a2103d32ca',
    messagingSenderId: '736748802815',
    projectId: 'fir-register-c3602',
    storageBucket: 'fir-register-c3602.firebasestorage.app',
    iosBundleId: 'com.example.gymunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU9J63C7nT5WWXnZIXZXZezbCY6XBQZHg',
    appId: '1:736748802815:ios:5f491fc97054a2103d32ca',
    messagingSenderId: '736748802815',
    projectId: 'fir-register-c3602',
    storageBucket: 'fir-register-c3602.firebasestorage.app',
    iosBundleId: 'com.example.gymunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_djTZ-ZBK8tabw_ccKZgyKEZpZVDU42U',
    appId: '1:736748802815:web:e8938aed1f83533c3d32ca',
    messagingSenderId: '736748802815',
    projectId: 'fir-register-c3602',
    authDomain: 'fir-register-c3602.firebaseapp.com',
    storageBucket: 'fir-register-c3602.firebasestorage.app',
  );
}
